deployedRegion: "default"

member:
  roles: [ "Server", "Controller", "Consumer" ]
  maxQps: 5000
  networkMBps: 30

vertxOptions:
  eventLoopPoolSize: 1
  workerPoolSize: 1
  internalBlockingPoolSize: 1
  blockedThreadCheckInterval: 1800000

verticleDeploymentOptions:
  instances: 1
  worker: false
  workerPoolSize: 2

# Refer Vertx DeliveryOptions for details, used for inter node communication.
deliveryOptions:
  timeoutMs: 10000
  tracingPolicy: "PROPAGATE"

producerOptions:
  producerCacheTtlSeconds: 3600

messagingStackOptions:
  providerClassName: "com.flipkart.varadhi.pulsar.PulsarStackProvider"
  configFile: "messaging.yml"

metaStoreOptions:
  providerClassName: "com.flipkart.varadhi.db.ZookeeperProvider"
  configFile: "metastore.yml"

zookeeperOptions:
  connectUrl: "${ZOOKEEPER_URL}"
  sessionTimeoutMs: 60000
  connectTimeoutMs: 2000

featureFlags:
  leanDeployment: false
  defaultOrg: "default"
  defaultTeam: "public"
  defaultProject: "public"

messageConfiguration:
  headers:
    allowedPrefix: [ "X_", "X-" ]
    msgId:
      value: "X_MESSAGE_ID"
      requiredBy: All
    groupId:
      value: "X_GROUP_ID"
      requiredBy: None
    callbackCodes:
      value: "X_CALLBACK_CODES"
      requiredBy: None
    requestTimeout:
      value: "X_REQUEST_TIMEOUT"
      requiredBy: None
    replyToHttpUri:
      value: "X_REPLY_TO_HTTP_URI"
      requiredBy: None
    replyToHttpMethod:
      value: "X_REPLY_TO_HTTP_METHOD"
      requiredBy: None
    replyTo:
      value: "X_REPLY_TO"
      requiredBy: None
    httpUri:
      value: "X_HTTP_URI"
      requiredBy: Queue
    httpMethod:
      value: "X_HTTP_METHOD"
      requiredBy: Queue
    httpContentType:
      value: "X_CONTENT_TYPE"
      requiredBy: None
    producerIdentity:
      value: "X_PRODUCE_IDENTITY"
      requiredBy: None
    produceRegion:
      value: "X_PRODUCE_REGION"
      requiredBy: None
    produceTimestamp:
      value: "X_PRODUCE_TIMESTAMP"
      requiredBy: None

  maxIdHeaderSize: 100
  maxRequestSize: 5242880
  filterNonCompliantHeaders: true

metricsExporterOptions:
  exporter: "otlp"
  otlp.url: "${OTEL_URL}"
  otlp.step: "20s"
  otlp.aggregationTemporality: "CUMULATIVE"
  otlp.resourceAttributes:
  otlp.headers:

tracesEnabled: true

operationsConfig:
  maxConcurrentOps: 2
  maxRetryAllowed: 3
  retryIntervalInSeconds: 10
  retryMinBackoffInSeconds: 10
  retryMaxBackOffInSeconds: 60

disabledAPIs: [ ]

httpServerOptions:
  port: 18488
  alpnVersions: [ "HTTP_1_1", "HTTP_2" ]
  decompressionSupported: false
  useAlpn: true
  tracingPolicy: "ALWAYS"

restOptions:
  defaultTopicCapacity:
    throughputKBps: 400
    qps: 100
    readFanOut: 2

authenticationOptions:
  configFile: "authn.yml"
  handlerProviderClassName: "com.flipkart.varadhi.web.authn.UserHeaderAuthenticationHandler"
  orgContextExemptionURLs:
    - path: ^\\/v1\\/orgs\$
      methodList:
        - POST

authorizationOptions:
  enabled: true
  providerClassName: "com.flipkart.varadhi.web.authz.DefaultAuthorizationProvider"
  configFile: "authorizationConfig.yml"
