# values for fcp deployment.
# value files order: common.values.yaml fcp.values.yaml

images:
  pullPolicy: IfNotPresent
  appImage:
    registry: jfrog.fkinternal.com
    repository: varadhi-oss/varadhi
    tag: 0.0.0-6unstable

deployment:
  name: server
  replicaCount: 3
  resources:
    requests:
      memory: 1G
      cpu: 1
    limits:
      memory: 1G
      cpu: 1
  service:
    annotations:
      elb.fcp/do-not-delete-vip: 'true'
      elb.fcp/mode: http
      elb.fcp/name: varadhi-oss-varadhi-srv-vip
      elb.fcp/scope: REGIONAL
      elb.fcp/frontend-port: '80'
      elb.fcp/backend-port: '18488'
      elb.fcp/health-check-port: '18488'
      elb.fcp/health-check-path: /v1/health-check
      elb.fcp/health-check-timeout: 1s
      elb.fcp/health-check-interval: 5s
      elb.fcp/load-balancing-algorithm: leastconn
      elb.fcp/capacity-scalar: '1'
    frontendPort: 8888

#############################################################################
#  Config Settings for respective Varadhi components and their dependencies
############################################################################

####################################################
# Varadhi app -- Server (rest api + producer) config
####################################################
varadhi:
  app:
    name: server
    configMapName: server
    configs:
      javaExtraOpts: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9990"
    debug: true
    httpServerOptions:
      port: 18488
      alpnVersions: [ "HTTP_1_1", "HTTP_2" ]
      decompressionSupported: false
      useAlpn: true
    authenticationEnabled: false
    authorizationEnabled: true
    authorization:
      superUsers: [ "thanos" ]
      providerClassName: "com.flipkart.varadhi.auth.DefaultAuthorizationProvider"
    messagingStackOptions:
      providerClassName: "com.flipkart.varadhi.pulsar.PulsarStackProvider"
    metaStoreOptions:
      providerClassName: "com.flipkart.varadhi.db.ZookeeperProvider"
    featureFlags:
      leanDeployment: false
    member:
      roles: [ "Server", "Controller" ]
      cpuCount: 1
      networkMBps: 100
    ports:
      jmx: 9990
      jvmDebug: 5005

#############################################
# Varadhi Server logging config
#############################################


#############################################
# Metastore config -- zookeeper
#############################################
metastore:
  configMapName: metastore
  zookeeper:
    connectUrl: "127.0.0.1:2181"
    sessionTimeoutMs: 60000
    connectTimeoutMs: 2000


#############################################
# Messaging stack config - pulsar
#############################################
messaging:
  configMapName: messaging
  pulsar:
    adminOptions:
      serviceHttpUrl: "http://192.168.1.3:8080"
      connectionTimeoutMs: 2000
      readTimeoutMs: 2000
      requestTimeoutMs: 2000
    clientOptions:
      serviceUrl: "http://192.168.1.3:8080"
      keepAliveIntervalSecs: 30                     # Pulsar default (30 secs)
      ioThreads: 2                                  # start with 2, might need further tuning (Pulsar default is 1).
      connectionsPerBroker: 1                       # Pulsar default is 1.
      maxConcurrentLookupRequests: 5000             # Pulsar default is 5000.
      maxLookupRequests: 50000                      # Pulsar default is 50000.
      maxLookupRedirects: 20                        # Pulsar default is 20.
      maxNumberOfRejectedRequestPerConnection: 50   # Pulsar default is 50.
      memoryLimit: 0                                # Pulsar default is no limit (0).
      operationTimeoutMs: 2000                      # keep it low to fail fast. Pulsar default is 30 Secs.
      connectionTimeoutMs: 2000                     # keep it low to fail fast. Pulsar default is 10 Secs.
      lookupTimeoutMs: 10000                        # 5 times operationTimeout
      initialBackoffIntervalMs: 500                 # some random value.
      maxBackoffIntervalMs: 100                     # half of operationTimeoutMs.

#############################################
# Authz provider config
#############################################
authzProvider:
  configMapName: authorization

otlpConfig: null
