receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus, debug]
