global:
  scrape_interval:     20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: 'varadhi-metrics'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
