global:
  scrape_interval:     250ms
  evaluation_interval: 250ms

scrape_configs:
  - job_name: 'varadhi-metrics'
    metrics_path: '/metrics'
    scrape_interval: 250ms
    static_configs:
      - targets: ['otel-collector:8889']
