# values for fcp deployment.
# value files order: common.values.yaml fcp.values.yaml

images:
  pullPolicy: IfNotPresent
  zookeeper:
    registry: jfrog.fkinternal.com
    repository: varadhi-oss/zookeeper
    tag: 3.7.0

zkDeployment:
  enabled: true
  name: zookeeper
  replicaCount: 3
  ports:
    http: 8000
    client: 2181
    follower: 2888
    leaderElection: 3888
  resources:
    requests:
      memory: 1G
      cpu: 1
    limits:
      memory: 1G
      cpu: 1
  volumes:
    persistence: true
    storageClassName: ssd-jbod-ext4-0
    storageClass:
    selector: { }
    data:
      name: data
      size: 10Mi
    dataLog:
      name: datalog
      size: 10Mi
    conf:
      name: zk-conf
    scripts:
      name: zk-scripts
  configMapName: zookeeper
  scriptsConfigMapName: zookeeper-scripts
  configData:
    clientPort: 2181
