name: Docker Image Build and/or Push

on:
  workflow_call:
    inputs:
      pushToDockerHub:
        description: 'Whether to push image to dockerhub'
        required: true
        type: boolean
      releaseVersion:
        description: 'Docker image tag'
        type: string
        required: true
    secrets:
      dockerHubToken:
        required: false

jobs:

  build:
  
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: 'gradle'
    - name: Setup Gradle 5.6.4
      uses: gradle/gradle-build-action@v2.4.2
      with:
        gradle-version: 5.6.4
    - name: Execute Gradle build
      run: ./gradlew clean build copyDependencies :server:copyJacocoAgent -x test
    - name: Build the Docker image
      run: docker build . --file setup/docker/Dockerfile --tag varadhi/varadhi:${{ inputs.releaseVersion }}
    - name: Push to DockerHub
      if: ${{ inputs.pushToDockerHub }} == true
      run: |
        docker login -u varadhi -p ${{ secrets.dockerHubToken }}
        docker push varadhi/varadhi:${{ inputs.releaseVersion }}
